package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Allure")
    void generatedTest() {
        step("open 'https://habr.com/test99998989898'", () -> {
            step("// todo: just add selenium action");
        });

        step("Set username 'Ivan'", () -> {
            step("// todo: just add selenium action");
        });

        step("Set password 'None_123456789'", () -> {
            step("// todo: just add selenium action");
        });

        step("Submit form", () -> {
            step("// todo: just add selenium action");
        });

        step("Verify successful authorization as 'Ivan'", () -> {
            step("// todo: just add selenium action");
        });

        step("do somesing", () -> {
            step("// todo: just add selenium action");
        });

        step("check blocks text", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://habr.com/test99998989898'", () ->
            open("https://habr.com/test99998989898"));

        step("Page title should have text 'Page not found / Habr'", () -> {
            String expectedTitle = "Page not found / Habr";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://habr.com/test99998989898'", () ->
            open("https://habr.com/test99998989898"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}